import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1773348231773 implements MigrationInterface {
    name = 'Init1773348231773'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "branch_id" uuid, "name" character varying(100) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "branch_id" uuid NOT NULL, "category_id" uuid, "name" character varying(150) NOT NULL, "sku" character varying(50), "description" text, "price_per_kg" numeric(10,2) NOT NULL DEFAULT '0', "price_unit" numeric(10,2) NOT NULL DEFAULT '0', "sale_type" character varying(20) NOT NULL, "stock" numeric(10,3) NOT NULL DEFAULT '0', "min_stock" numeric(10,3) NOT NULL DEFAULT '0', "image_url" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_c44ac33a05b144dd0d9ddcf9327" UNIQUE ("sku"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cash_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "branch_id" uuid NOT NULL, "user_id" uuid NOT NULL, "opening_amount" numeric(10,2) NOT NULL, "closing_amount" numeric(10,2), "calculated_amount" numeric(10,2), "difference" numeric(10,2), "opened_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "closed_at" TIMESTAMP WITH TIME ZONE, "status" character varying(20) NOT NULL DEFAULT 'OPEN', "notes" text, CONSTRAINT "PK_946ea5ce864b10fb70162708448" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "document_type" character varying(20) NOT NULL DEFAULT 'DNI', "document_number" character varying(20), "full_name" character varying(200), "business_name" character varying(200), "email" character varying(150), "phone" character varying(20), "address" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sale_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" numeric(10,3) NOT NULL, "unitPrice" numeric(10,2) NOT NULL, "totalPrice" numeric(10,2) NOT NULL, "sale_id" uuid, "product_id" uuid, CONSTRAINT "PK_5a7dc5b4562a9e590528b3e08ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sunat_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sale_id" uuid NOT NULL, "sunat_status" character varying(20) NOT NULL DEFAULT 'PENDING', "xml_filename" character varying(100), "cdr_filename" character varying(100), "digest_value" text, "sunat_description" text, "sunat_code" character varying(10), "sent_at" TIMESTAMP WITH TIME ZONE, "response_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "REL_db7badd8ea60d02d33b9d76a9a" UNIQUE ("sale_id"), CONSTRAINT "PK_8871d501122f761aaabca45f519" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "branch_id" uuid NOT NULL, "seller_id" uuid, "cash_session_id" uuid NOT NULL, "customer_id" uuid, "payment_method" character varying(20) NOT NULL, "receipt_type" character varying(20) NOT NULL, "receipt_series" character varying(10), "receipt_number" character varying(20), "subtotal" numeric(10,2) NOT NULL, "igv" numeric(10,2) NOT NULL, "total" numeric(10,2) NOT NULL, "cash_amount" numeric(10,2) NOT NULL DEFAULT '0', "digital_amount" numeric(10,2) NOT NULL DEFAULT '0', "status" character varying(20) NOT NULL DEFAULT 'COMPLETED', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "branches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(150) NOT NULL, "address" text, "code" character varying(20), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_9c06cbb83feb2f0be6263bd47ee" UNIQUE ("code"), CONSTRAINT "PK_7f37d3b42defea97f1df0d19535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "description" text, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "branch_id" uuid, "role_id" uuid, "full_name" character varying(150) NOT NULL, "username" character varying(100) NOT NULL, "password_hash" text NOT NULL, "pin_code" character varying(10), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "supplier_invoice_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" numeric(10,3) NOT NULL, "unit_cost" numeric(10,2) NOT NULL, "total_cost" numeric(10,2) NOT NULL, CONSTRAINT "PK_1e1e13a8ff2efcfe38b1e62f2ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "supplier_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_id" uuid NOT NULL, "invoice_id" uuid, "cash_session_id" uuid NOT NULL, "payment_method" character varying(20) NOT NULL, "amount" numeric(10,2) NOT NULL, "reference" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_76e86f3194494faf999c652dbf9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "supplier_invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "invoice_number" character varying(50), "invoice_date" TIMESTAMP WITH TIME ZONE, "subtotal" numeric(10,2) NOT NULL, "igv" numeric(10,2) NOT NULL, "total" numeric(10,2) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'PENDING', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_08f98a1a117d65ab2f4452247a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "branch_id" uuid, "document_type" character varying(20) NOT NULL DEFAULT 'RUC', "document_number" character varying(20), "business_name" character varying(200) NOT NULL, "contact_name" character varying(150), "email" character varying(150), "phone" character varying(20), "address" text, "bank_account" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "employees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "branch_id" uuid, "salary" numeric(10,2) NOT NULL, "payment_frequency" character varying(20) NOT NULL DEFAULT 'MONTHLY', "hire_date" date, "status" character varying(20) NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payroll_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "employee_id" uuid NOT NULL, "cash_session_id" uuid NOT NULL, "payment_type" character varying(20) NOT NULL, "amount" numeric(10,2) NOT NULL, "note" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_41e701544ef7ee7160a4af11995" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_moments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "user_id" uuid, "movement_type" character varying(20) NOT NULL, "reference_id" uuid, "note" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_dc3febe255e7085fb6f89d47f15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "expense_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "PK_d0ef31e189d9523461215b62775" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "branch_id" uuid NOT NULL, "category_id" uuid NOT NULL, "cash_session_id" uuid NOT NULL, "amount" numeric(10,2) NOT NULL, "payment_method" character varying(20) NOT NULL DEFAULT 'EFECTIVO', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_94c3ceb17e3140abc9282c20610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cash_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cash_session_id" uuid NOT NULL, "user_id" uuid NOT NULL, "movement_type" character varying NOT NULL, "amount" numeric(10,2) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_25faead19e1ff74153a01604d37" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cash_counts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "cash_session_id" uuid NOT NULL, "bill_10" integer NOT NULL DEFAULT '0', "bill_20" integer NOT NULL DEFAULT '0', "bill_50" integer NOT NULL DEFAULT '0', "bill_100" integer NOT NULL DEFAULT '0', "bill_200" integer NOT NULL DEFAULT '0', "coin_total" numeric(10,2) NOT NULL DEFAULT '0', "counted_total" numeric(10,2) NOT NULL, "expected_total" numeric(10,2) NOT NULL, "difference" numeric(10,2) NOT NULL, "observation" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2316859396814c38ccd52cedfe5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "branch_id" uuid NOT NULL, "method" character varying(20), "check_in" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "check_out" TIMESTAMP WITH TIME ZONE, "work_hours" numeric(5,2), CONSTRAINT "PK_483ed97cd4cd43ab4a117516b69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_0011937b9b4cd88d39accdd6edf" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_de720484cb95d8752861e507921" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" ADD CONSTRAINT "FK_11f61ce8c6dc0bfcbed082ef7d5" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" ADD CONSTRAINT "FK_04ff8cefb5ce273f29487898ef9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_c210a330b80232c29c2ad68462a" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD CONSTRAINT "FK_4ecae62db3f9e9cc9a368d57adb" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sunat_documents" ADD CONSTRAINT "FK_db7badd8ea60d02d33b9d76a9af" FOREIGN KEY ("sale_id") REFERENCES "sales"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_236f3154522de80a98f87c66b84" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_fbcb737b3ecc7c968b0dc167122" FOREIGN KEY ("seller_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_4e85abc6ca85052e6703762ec30" FOREIGN KEY ("cash_session_id") REFERENCES "cash_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_c51005b2b06cec7aa17462c54f5" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_5a58f726a41264c8b3e86d4a1de" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_invoice_item" ADD CONSTRAINT "FK_9d2e7c4c94b0d59ad23fe316e1f" FOREIGN KEY ("invoice_id") REFERENCES "supplier_invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_invoice_item" ADD CONSTRAINT "FK_86fb00e5c49207045f25b37a3c4" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_payments" ADD CONSTRAINT "FK_220694212ec38b4aa2fb02ed622" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_payments" ADD CONSTRAINT "FK_f2cd5b3aae1aadab76c74de8146" FOREIGN KEY ("invoice_id") REFERENCES "supplier_invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_payments" ADD CONSTRAINT "FK_bef96c9a202900e742fe777148c" FOREIGN KEY ("cash_session_id") REFERENCES "cash_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_invoices" ADD CONSTRAINT "FK_1c85b2d278b6b6f3ab2ea9dc582" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_invoices" ADD CONSTRAINT "FK_11bde8c1e9b966acde4a6145e8e" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_ce35fd787e09aecdb311aaff66c" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_2d83c53c3e553a48dadb9722e38" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_457a39c666de2686596e502eb8c" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payroll_payments" ADD CONSTRAINT "FK_5c49db801fe1b64db0d78cf6d3b" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payroll_payments" ADD CONSTRAINT "FK_fd0600186a4b5e5de1017d13611" FOREIGN KEY ("cash_session_id") REFERENCES "cash_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_moments" ADD CONSTRAINT "FK_10ab705d7228c49dd00a35371ba" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_moments" ADD CONSTRAINT "FK_b9d60bcf5b69b8308746df06140" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_moments" ADD CONSTRAINT "FK_23f9bf83233fc4abe30b0770128" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_866a3b82ff438efc19c2398cda6" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_5d1f4be708e0dfe2afa1a3c376c" FOREIGN KEY ("category_id") REFERENCES "expense_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_051d3c1315bc8d8b0567feff198" FOREIGN KEY ("cash_session_id") REFERENCES "cash_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_movements" ADD CONSTRAINT "FK_fa6a0c146567090acf8a03e01c2" FOREIGN KEY ("cash_session_id") REFERENCES "cash_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_movements" ADD CONSTRAINT "FK_798030be2b2ae79a0b538e98f73" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_counts" ADD CONSTRAINT "FK_4e3647b75656eee3e1c1d6ce37a" FOREIGN KEY ("cash_session_id") REFERENCES "cash_sessions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD CONSTRAINT "FK_aa902e05aeb5fde7c1dd4ced2b7" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD CONSTRAINT "FK_dc7f59ed9f70ec2c5e93066a211" FOREIGN KEY ("branch_id") REFERENCES "branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "attendances" DROP CONSTRAINT "FK_dc7f59ed9f70ec2c5e93066a211"`);
        await queryRunner.query(`ALTER TABLE "attendances" DROP CONSTRAINT "FK_aa902e05aeb5fde7c1dd4ced2b7"`);
        await queryRunner.query(`ALTER TABLE "cash_counts" DROP CONSTRAINT "FK_4e3647b75656eee3e1c1d6ce37a"`);
        await queryRunner.query(`ALTER TABLE "cash_movements" DROP CONSTRAINT "FK_798030be2b2ae79a0b538e98f73"`);
        await queryRunner.query(`ALTER TABLE "cash_movements" DROP CONSTRAINT "FK_fa6a0c146567090acf8a03e01c2"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_051d3c1315bc8d8b0567feff198"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_5d1f4be708e0dfe2afa1a3c376c"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_866a3b82ff438efc19c2398cda6"`);
        await queryRunner.query(`ALTER TABLE "stock_moments" DROP CONSTRAINT "FK_23f9bf83233fc4abe30b0770128"`);
        await queryRunner.query(`ALTER TABLE "stock_moments" DROP CONSTRAINT "FK_b9d60bcf5b69b8308746df06140"`);
        await queryRunner.query(`ALTER TABLE "stock_moments" DROP CONSTRAINT "FK_10ab705d7228c49dd00a35371ba"`);
        await queryRunner.query(`ALTER TABLE "payroll_payments" DROP CONSTRAINT "FK_fd0600186a4b5e5de1017d13611"`);
        await queryRunner.query(`ALTER TABLE "payroll_payments" DROP CONSTRAINT "FK_5c49db801fe1b64db0d78cf6d3b"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_457a39c666de2686596e502eb8c"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_2d83c53c3e553a48dadb9722e38"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_ce35fd787e09aecdb311aaff66c"`);
        await queryRunner.query(`ALTER TABLE "supplier_invoices" DROP CONSTRAINT "FK_11bde8c1e9b966acde4a6145e8e"`);
        await queryRunner.query(`ALTER TABLE "supplier_invoices" DROP CONSTRAINT "FK_1c85b2d278b6b6f3ab2ea9dc582"`);
        await queryRunner.query(`ALTER TABLE "supplier_payments" DROP CONSTRAINT "FK_bef96c9a202900e742fe777148c"`);
        await queryRunner.query(`ALTER TABLE "supplier_payments" DROP CONSTRAINT "FK_f2cd5b3aae1aadab76c74de8146"`);
        await queryRunner.query(`ALTER TABLE "supplier_payments" DROP CONSTRAINT "FK_220694212ec38b4aa2fb02ed622"`);
        await queryRunner.query(`ALTER TABLE "supplier_invoice_item" DROP CONSTRAINT "FK_86fb00e5c49207045f25b37a3c4"`);
        await queryRunner.query(`ALTER TABLE "supplier_invoice_item" DROP CONSTRAINT "FK_9d2e7c4c94b0d59ad23fe316e1f"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_5a58f726a41264c8b3e86d4a1de"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_c51005b2b06cec7aa17462c54f5"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_4e85abc6ca85052e6703762ec30"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_fbcb737b3ecc7c968b0dc167122"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_236f3154522de80a98f87c66b84"`);
        await queryRunner.query(`ALTER TABLE "sunat_documents" DROP CONSTRAINT "FK_db7badd8ea60d02d33b9d76a9af"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_4ecae62db3f9e9cc9a368d57adb"`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP CONSTRAINT "FK_c210a330b80232c29c2ad68462a"`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" DROP CONSTRAINT "FK_04ff8cefb5ce273f29487898ef9"`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" DROP CONSTRAINT "FK_11f61ce8c6dc0bfcbed082ef7d5"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_de720484cb95d8752861e507921"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_0011937b9b4cd88d39accdd6edf"`);
        await queryRunner.query(`DROP TABLE "attendances"`);
        await queryRunner.query(`DROP TABLE "cash_counts"`);
        await queryRunner.query(`DROP TABLE "cash_movements"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP TABLE "expense_categories"`);
        await queryRunner.query(`DROP TABLE "stock_moments"`);
        await queryRunner.query(`DROP TABLE "payroll_payments"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP TABLE "supplier_invoices"`);
        await queryRunner.query(`DROP TABLE "supplier_payments"`);
        await queryRunner.query(`DROP TABLE "supplier_invoice_item"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "branches"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP TABLE "sunat_documents"`);
        await queryRunner.query(`DROP TABLE "sale_items"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "cash_sessions"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "categories"`);
    }

}
